[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./script/scriptsData.json"}]

remappings=["@openzeppelin/=lib/openzeppelin-contracts/contracts"]

[fuzz]
runs = 500

[invariant]
runs = 5 #5
depth = 150 #150
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
